language: swift
osx_image: xcode9.3
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
before_script:
  # bootstrap the dependencies for the project
  # you can remove if you don't have dependencies
  - carthage bootstrap
script: xcodebuild clean build -sdk iphonesimulator -project BookPlayer.xcodeproj -scheme BookPlayer CODE_SIGNING_REQUIRED=NO
